version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
    overwrite: yes

permissions:
  - object: /home/ubuntu/build/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  # BeforeInstall:
  #   - location: scripts/cleanup.sh
  #     timeout: 300
  # AfterInstall:
  #   - location: scripts/after-deploy.sh
  #     timeout: 300

  # 주석
